import os

SPOTIFY_CLIENT_ID = os.environ["SPOTIFY_CLIENT_ID"]
SPOTIFY_CLIENT_SECRET = os.environ["SPOTIFY_CLIENT_SECRET"]
SPOTIFY_SHAZAM_PLAYLIST_ID = os.environ["SPOTIFY_SHAZAM_PLAYLIST_ID"]
SPOTIFY_STAR_PLAYLIST_ID = os.environ["SPOTIFY_STAR_PLAYLIST_ID"]
TICKETMASTER_KEY = os.environ["TICKETMASTER_KEY"]
